# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /home/mohamed/yocto/layers/poky/meta \
  /home/mohamed/yocto/layers/poky/meta-poky \
  /home/mohamed/yocto/layers/poky/meta-yocto-bsp \
  /home/mohamed/yocto/layers/meta-openembedded/meta-oe \
  /home/mohamed/yocto/layers/meta-openembedded/meta-python \
  /home/mohamed/yocto/layers/meta-qt6 \
  /home/mohamed/yocto/layers/meta-bbb-automotive \
  "
