# ==============================================================================
# FICHIER DE CONFIGURATION DU LAYER : meta-bbb-automotive
# Ce fichier permet à BitBake de découvrir et d'indexer ce layer personnalisé.
# ==============================================================================

# 1. AJOUT DES CHEMINS GLOBAUX
# On ajoute le dossier de ce layer au chemin de recherche global de Yocto (BBPATH).
# Cela permet à BitBake de trouver les classes (.bbclass) et les configurations de machines.
BBPATH .= ":${LAYERDIR}"

# 2. LOCALISATION DES RECETTES
# On indique à BitBake où chercher les recettes (.bb) et les extensions (.bbappend).
# La syntaxe "recipes-*/*/*.bb" permet de scanner toute l'arborescence du layer.
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

# 3. DÉCLARATION ET RECONNAISSANCE DU LAYER
# On donne un nom unique (une collection) à ce layer pour l'identifier dans le build.
BBFILE_COLLECTIONS += "meta-bbb-automotive"

# On lie ce nom unique au chemin physique du dossier du layer sur le disque dur.
BBFILE_PATTERN_meta-bbb-automotive = "^${LAYERDIR}/"

# On définit la priorité de ce layer (6 est la valeur standard).
# Si une recette porte le même nom dans un autre layer, la priorité décide laquelle gagne.
BBFILE_PRIORITY_meta-bbb-automotive = "6"

# 4. GESTION DES DÉPENDANCES ET COMPATIBILITÉS
# On déclare que ce layer a impérativement besoin de la couche de base "core" (Poky) pour fonctionner.
LAYERDEPENDS_meta-bbb-automotive = "core"

# On certifie que ce layer est compatible avec la version spécifique "Scarthgap" de Yocto (LTS 2024/2026).
# BitBake bloquera le build si vous tentez d'utiliser ce layer sur une autre version.
LAYERSERIES_COMPAT_meta-bbb-automotive = "scarthgap"